name: Update changelog on published release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: changelog-gh-pages
  cancel-in-progress: false

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog from latest release
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_summary_template: "chore: update changelog for %s"
          header: |
            <style>
              :root {
                --font-sans: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Inter", "Segoe UI", Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji";
                --text: #0f172a;         /* slate-900 */
                --muted: #475569;        /* slate-600 */
                --link: #2563eb;         /* blue-600 */
                --link-hover: #1d4ed8;   /* blue-700 */
                --border: rgba(15, 23, 42, 0.08);
              }

              /* Base typography */
              html, body {
                padding: 0;
                margin: 0;
                background: transparent;
              }
              body {
                font-family: var(--font-sans);
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
                text-rendering: optimizeLegibility;
                font-size: 16px;
                line-height: 1.6;
                color: var(--text);
                max-width: 820px;
                margin: 24px auto;
                padding: 0 16px;
              }

              /* Headings */
              h1, h2, h3, h4 {
                color: var(--text);
                letter-spacing: -0.02em;
              }
              h1:first-of-type { /* hide GitHub release title duplicate */
                display: none;
              }
              h1 {
                font-weight: 750;
                font-size: clamp(26px, 3.6vw, 34px);
                line-height: 1.25;
                margin: 8px 0 16px;
              }
              h2 {
                font-weight: 700;
                font-size: clamp(22px, 2.8vw, 28px);
                margin: 28px 0 10px;
              }
              h3 {
                font-weight: 650;
                font-size: 20px;
                margin: 20px 0 8px;
              }

              /* Text and lists */
              p { margin: 10px 0 14px; color: var(--text); }
              strong { font-weight: 650; }
              ul, ol { padding-left: 1.25rem; margin: 8px 0 14px; }
              li { margin: 6px 0; }
              blockquote {
                margin: 12px 0;
                padding: 8px 12px;
                border-left: 3px solid var(--border);
                color: var(--muted);
              }

              /* Links */
              a, :link {
                color: var(--link);
                text-decoration: underline;
                text-underline-offset: 2px;
                text-decoration-thickness: 1px;
                transition: color .2s ease, text-decoration-color .2s ease;
              }
              a:hover { color: var(--link-hover); }
              a:focus-visible {
                outline: none;
                box-shadow: 0 0 0 3px rgba(37, 99, 235, .25);
                border-radius: 6px;
              }

              /* Media */
              img {
                max-width: 100%;
                height: auto;
                border-radius: 10px;
              }

              /* Code */
              code, pre, kbd, samp {
                font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
              }
              pre {
                background: rgba(15, 23, 42, 0.04);
                border: 1px solid var(--border);
                border-radius: 10px;
                padding: 12px 14px;
                overflow: auto;
              }
              code {
                background: rgba(15, 23, 42, 0.04);
                border: 1px solid var(--border);
                border-radius: 6px;
                padding: 1px 6px;
              }

              /* Utility */
              .my-5 { margin: unset !important; }

              /* Dark mode */
              @media (prefers-color-scheme: dark) {
                :root {
                  --text: #e5e7eb;          /* gray-200 */
                  --muted: #9ca3af;         /* gray-400 */
                  --link: #60a5fa;          /* blue-400 */
                  --link-hover: #93c5fd;    /* blue-300 */
                  --border: rgba(148, 163, 184, 0.18);
                }
                pre, code {
                  background: rgba(148, 163, 184, 0.08);
                }
              }

              /* Donation button */
              .donation-link {
                position: relative;
                display: inline-flex;
                align-items: center;
                justify-content: center;
                gap: 8px;
                padding: 10px 16px;
                min-width: 180px;
                border-radius: 10px;
                background: linear-gradient(135deg, rgba(255,255,255,0.92) 0%, rgba(248,250,252,0.88) 100%);
                color: #0b1324 !important; /* readable on light background */
                font-size: 0.95em;
                font-weight: 700;
                text-decoration: none;
                border: 1px solid var(--border);
                box-shadow:
                  0 6px 24px rgba(0,0,0,0.10),
                  0 1px 3px rgba(0,0,0,0.08),
                  inset 0 1px 0 rgba(255,255,255,0.65);
                overflow: hidden;
                transition: transform .35s cubic-bezier(.25,.46,.45,.94), box-shadow .35s cubic-bezier(.25,.46,.45,.94);
                backdrop-filter: blur(4px);
                letter-spacing: 0.02em;
              }
              .donation-link span {
                position: relative;
                z-index: 2; /* keep text above overlays */
                transition: color .35s ease, filter .35s ease;
              }
              .donation-link::before {
                content: '';
                position: absolute;
                inset: 0;
                background: linear-gradient(
                  to bottom,
                  #61BB46 0%,
                  #61BB46 16.66%,
                  #FDB827 16.66%,
                  #FDB827 33.33%,
                  #F5821F 33.33%,
                  #F5821F 50%,
                  #E03A3E 50%,
                  #E03A3E 66.66%,
                  #963D97 66.66%,
                  #963D97 83.33%,
                  #009DDC 83.33%,
                  #009DDC 100%
                );
                transform: translateY(100%);
                transition: transform .45s cubic-bezier(.25,.46,.45,.94);
                z-index: 1;
                opacity: 0.95;
              }
              .donation-link::after {
                content: '';
                position: absolute;
                inset: -2px;
                background: linear-gradient(45deg,#61BB46,#FDB827,#F5821F,#E03A3E,#963D97,#009DDC);
                border-radius: inherit;
                z-index: 0;
                opacity: 0;
                filter: blur(10px);
                transition: opacity .45s ease;
              }
              .donation-link:hover::before {
                transform: translateY(0%); /* reveal rainbow overlay */
              }
              .donation-link:hover::after {
                opacity: .28; /* subtle glow */
              }
              .donation-link:hover {
                transform: translateY(-1px);
                box-shadow:
                  0 10px 32px rgba(0,0,0,0.14),
                  0 4px 12px rgba(0,0,0,0.10),
                  inset 0 1px 0 rgba(255,255,255,0.25);
                border-color: rgba(209, 213, 219, 0.75);
              }
              .donation-link:hover span {
                color: #ffffff;                 /* ensure readable on overlay */
                filter: drop-shadow(0 1px 2px rgba(0,0,0,0.35));
              }
              @media (prefers-color-scheme: dark) {
                .donation-link {
                  background: linear-gradient(135deg, rgba(17,24,39,0.7) 0%, rgba(31,41,55,0.7) 100%);
                  color: #f3f4f6 !important;
                  border-color: var(--border);
                  box-shadow:
                    0 6px 24px rgba(0,0,0,0.35),
                    0 1px 3px rgba(0,0,0,0.25),
                    inset 0 1px 0 rgba(255,255,255,0.05);
                }
                .donation-link:hover {
                  border-color: rgba(148, 163, 184, 0.45);
                }
              }
            </style>

            <!-- Use an anchor tag and wrap text in a span so it stays above overlays -->
            <a
              class="donation-link"
              href="https://buymeacoffee.com/turtle.key"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Support turtle-key on Buy Me a Coffee"
            >
              <span>❤️ Support turtle-key</span>
            </a>

      - name: Fix workspace permissions
        run: |
          sudo chown -R $USER:$USER .
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Verify CHANGELOG.md exists
        run: |
          test -s CHANGELOG.md || { echo "CHANGELOG.md was not generated or is empty"; exit 1; }

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate CHANGELOG.html
        run: |
          npx --yes marked@12.0.2 --gfm CHANGELOG.md > CHANGELOG.html
          test -s CHANGELOG.html || { echo "CHANGELOG.html generation failed"; exit 1; }

      - name: Commit and push to gh-pages
        env:
          TAG_NAME: ${{ github.event.release.tag_name || 'manual trigger' }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add CHANGELOG.md CHANGELOG.html
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git pull --rebase origin gh-pages || true
          git commit -m "chore: update changelog for ${TAG_NAME}"
          git push origin gh-pages
