name: Update changelog on published release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Checkout gh-pages branch
        run: git checkout gh-pages

      - name: Update changelog from release
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.REPO_TOKEN }}
          commit_summary_template: "chore: update changelog for %s"
          header: |
            <style>
              h1:first-of-type {
                display: none;
              }
              .my-5 {
                margin: unset !important;
              }
              .markdown-body img {
                max-width: 50%;
              }
              @media (prefers-color-scheme: dark) {
                body {
                  color-scheme: dark;
                  color: white;
                  background: transparent;
                }
                a, :link {
                  color: #419cff;
                }
                a:active, link:active {
                  color: #ff1919;
                }
              }
              .donation-link {
                position: relative;
                display: inline-flex;
                align-items: center;
                justify-content: center;
                padding: 8px 16px;
                min-width: 180px;
                border-radius: 8px;
                background: linear-gradient(135deg, rgba(255,255,255,0.9) 0%, rgba(248,250,252,0.8) 100%);
                color: #000 !important;
                font-size: 0.9em;
                font-weight: bold;
                text-decoration: none;
                border: 1px solid rgba(209, 213, 219, 0.6);
                box-shadow: 
                  0 4px 20px rgba(0,0,0,0.08),
                  0 1px 3px rgba(0,0,0,0.1),
                  inset 0 1px 0 rgba(255,255,255,0.6);
                overflow: hidden;
                transition: all 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94);
                backdrop-filter: blur(4px);
                letter-spacing: 0.025em;
              }
              
              /* Rainbow overlay animation */
              .donation-link::before {
                content: '';
                position: absolute;
                top: 0; left: 0; right: 0; bottom: 0;
                background: linear-gradient(
                  to bottom,
                  #61BB46 0%,
                  #61BB46 16.66%,
                  #FDB827 16.66%,
                  #FDB827 33.33%,
                  #F5821F 33.33%,
                  #F5821F 50%,
                  #E03A3E 50%,
                  #E03A3E 66.66%,
                  #963D97 66.66%,
                  #963D97 83.33%,
                  #009DDC 83.33%,
                  #009DDC 100%
                );
                transform: translateY(-100%);
                transition: transform 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94);
                z-index: 1;
                border-radius: inherit;
                opacity: 0.95;
              }
              
              .donation-link:hover::before {
                transform: translateY(0%);
              }
              
              .donation-link:not(:hover)::before {
                transform: translateY(100%);
              }
              
              /* Glow effect */
              .donation-link::after {
                content: '';
                position: absolute;
                top: -2px; left: -2px; right: -2px; bottom: -2px;
                background: linear-gradient(
                  45deg,
                  #61BB46,
                  #FDB827,
                  #F5821F,
                  #E03A3E,
                  #963D97,
                  #009DDC
                );
                border-radius: inherit;
                z-index: -1;
                opacity: 0;
                filter: blur(8px);
                transition: opacity 0.5s ease;
              }
              
              .donation-link:hover::after {
                opacity: 0.3;
              }
              
              .donation-link:hover {
                transform: translateY(-1px);
                box-shadow: 
                  0 8px 30px rgba(0,0,0,0.12),
                  0 4px 12px rgba(0,0,0,0.08),
                  inset 0 1px 0 rgba(255,255,255,0.2);
                border-color: rgba(209, 213, 219, 0.8);
                color: white !important;
              }
              
              .donation-link span {
                position: relative;
                z-index: 10;
                transition: all 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94);
              }
              
              .donation-link:hover span {
                filter: drop-shadow(0 1px 2px rgba(0,0,0,0.3));
              }
            </style>
            <div class="donation-link" target="_blank">❤️ Support turtle-key at https://buymeacoffee.com/turtle.key</div>

      - name: Set file permissions
        run: sudo chown -R $(whoami) .

      - name: Commit changes
        run: |
          git config --global user.name "Mihai Ghețu"
          git config --global user.email "turtle-key@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.event.release.tag_name || 'manual trigger' }}" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
